------------------------------
-- Core Analysis 
------------------------------

-- Finding total revenue
select sum(Quantity * unitprice) as TotalRevenue
from ecommerce_clean;

-- Finding Total number of orders
select count(distinct(invoiceno)) 
from ecommerce_clean;

-- Finding Total no. of customers
select count(distinct(customerID)) 
from ecommerce_clean;

-- Average order value (identified and unidentified customers)
Select Sum(Quantity * UnitPrice)/count(distinct(invoiceno)) as avg_order_value
from ecommerce_clean;

-- Average revenue per customer
select Sum(Quantity * UnitPrice)/count(distinct(customerID)) as avg_rev_per_customer
from ecommerce_customers;

-- Number of orders per customer
select COUNT(DISTINCT InvoiceNo) / COUNT(DISTINCT CustomerID) as orders_per_customer
from ecommerce_customers; 

-- Total Revenue from unidentified customers
select sum(Quantity * UnitPrice)
from ecommerce_clean where customerId is null;

-- average order value for unidentified customers
select sum(Quantity * unitprice)/count(distinct(invoiceno)) as AOV_Unidentified_customers
from ecommerce_clean 
where customerid is null;

-- AOV for identified (alone) customers
select sum(Quantity * UnitPrice) / count(DISTINCT InvoiceNo)
from ecommerce_customers;

-- number of orders where customers are unidentified 
select count(distinct(invoiceno)) 
from ecommerce_clean
where customerid is null;

-- number of orders where customers are identified 
select count(distinct(invoiceno)) 
from ecommerce_customers;

-- number of identified customers 
select count(DISTINCT(customerID)) 
from ecommerce_customers;

-- Revenue generated by top 10 customers
select customerID, sum(quantity*unitprice) as Revenue
from ecommerce_customers
group by customerID
order by Revenue Desc
limit 10;

-- total revenue of top 10 customers 
select sum(revenue) from 
(select customerID, sum(quantity*unitprice) as Revenue
from ecommerce_customers
group by customerID
order by Revenue Desc
limit 10)t;



